package com.example.plugins

import com.example.routing.*
import com.example.routing.EPL.*
import com.example.routing.LaLiga.*
import com.example.routing.SerieA.*
import io.ktor.server.routing.*
import io.ktor.server.application.*

fun Application.configureRouting() {
    routing {
        getAllPlayers()
        getPlayer()
        addNewPlayer()
        deletePlayer()
        homePage()
        deleteLeague()
        addNewLeague()
        getLeague()
        getAllLeagues()
        getAllTeams()
        getTeam()
        deleteTeam()
        addNewTeam()
        getAllMuPlayers()
        MuHistory()
        getDefendersMu()
        getMidfieldersMu()
        getForwardsMu()
        getGoalkeepersMu()
        getGoalkeepersLiv()
        getForwardsLiv()
        getMidfieldersLiv()
        getDefendersLiv()
        getAllLivPlayers()
        livHistory()
        arsHistory()
        getGoalkeepersArs()
        getForwardsArs()
        getMidfieldersArs()
        getDefendersArs()
        getAllArsPlayers()
        getGoalkeepersChe()
        getForwardsChe()
        getMidfieldersChe()
        getDefendersChe()
        getAllChePlayers()
        cheHistory()
        getGoalkeepersMc()
        getForwardsMc()
        getMidfieldersMc()
        getDefendersMc()
        getAllMcPlayers()
        mcHistory()
        getGoalkeepersNap()
        getForwardsNap()
        getMidfieldersNap()
        getDefendersNap()
        getAllNapPlayers()
        napHistory()
        intHistory()
        getAllIntPlayers()
        getGoalkeepersInt()
        getForwardsInt()
        getMidfieldersInt()
        getDefendersInt()
        getGoalkeepersJuv()
        getForwardsJuv()
        getMidfieldersJuv()
        getDefendersJuv()
        getAllJuvPlayers()
        juvHistory()
        getGoalkeepersMil()
        getForwardsMil()
        getMidfieldersMil()
        getDefendersMil()
        getAllMilPlayers()
        milHistory()
        getGoalkeepersAtlM()
        getForwardsAtlM()
        getMidfieldersAtlM()
        getDefendersAtlM()
        getAllAtlMPlayers()
        atlMHistory()
        getGoalkeepersRma()
        getForwardsRma()
        getMidfieldersRma()
        getDefendersRma()
        getAllRmaPlayers()
        rmaHistory()
        getAllEPLClubs()
        getAllLaLigaClubs()
        getGoalkeepersBar()
        getForwardsBar()
        getMidfieldersBar()
        getDefendersBar()
        getAllBarPlayers()
        barHistory()
        getAllSerieAClubs()
    }
}

